---
version: "3"

services:
  pihole:
    container_name: Pi-Hole_Unbound
    image: cbcrowe/pihole-unbound:latest
    hostname: pihole.olympus.local
    network_mode: "bridge"
 
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "9080:80/tcp"
      - "9443:443/tcp"
    
    environment:
      TZ: 'Europe/Paris'
      ServerIP: '192.168.1.142'
      DNSSEC: 'true'
      DNS1:  '127.0.0.1#5335'

    volumes:
      - '/portainer/PiHole/etc:/etc/pihole'
      - '/portainer/PiHole/dnsmasq:/etc/dnsmasq.d'
      - '/portainer/PiHole/Certificates:/etc/certificates'
 #     - '/portainer/PiHole/lighttpd/external.conf/:/etc/lighttpd/external.conf'
 
    restart: unless-stopped
